policies:
  - type: commit
    spec:
      headerLength: 89
      dco: true
      gpg: false
      imperative: true
      maximumOfOneCommit: true
      requireCommitBody: true
      conventional:
        types:
          - chore
          - docs
          - perf
          - refactor
          - style
          - test
        scopes:
          - '*'
  - type: license
    spec:
      skipPaths:
        - .git/
      includeSuffixes:
        - .go
      header: |
        // CHANGE ME.
